### ISSUE TITLE
WS2812FX for Arduino Micro

### ISSUE THREAD

**Issue by HAMUZAO** [kitesurfer1404/WS2812FX#103]
Hello & thank you for this amazing animation library ^_^

I had a little issue with memory when i was trying to upload the a little WS2812FX code to my Arduino Micro & the Arduino IDE alert me that my code is more bigger than the allowed memory in Arduino Micro.

I wish to know if it is possible to have a way to remove some unecessary animations to save some space without having compilation errors please ^^

Thank you

**Comment by moose4lord** [comment]
@HAMUZAO, there is an option to reduce the library's memory footprint by removing some of the WS2812FX modes linked in your sketch. If you add "#define REDUCED_MODES" before "#include <WS2812FX.h>" in your sketch, the **BREATH**, **RUNNING_LIGHTS** and **ICU** modes will not be linked to your sketch, which reduces the amount of flash memory consumed by WS2812FX by about 2000 bytes.

```c++
#define REDUCED_MODES
#include <WS2812FX.h>
...
```

**Comment by HAMUZAO** [comment]
@moose4lord  Thanks for the help ^^
I tired your instruction & it helped a lot to reduce the code from 107% to 100% But i still cant upload it to Arduino Micro & the compiler tell me that my sketch is big that the allowed program memory Lol

I deleted all the unecessary codes & lines in my code to save space & i see that i cant go more than that !
I need to remove more animations to save 188 byte at least ..
Is that possible !?

> The sketch uses 28860 bytes (100%) of the program storage space. The maximum is 28672 bytes.
> Global variables use 982 bytes (38%) of dynamic memory, leaving 1578 bytes for local variables. The maximum is 2560 bytes.
> Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for discount tips.
> Compilation error for Arduino / Genuino Micro board

**Comment by moose4lord** [comment]
The Arduino Micro and Leonardo are challenging to work with. They have 32k of flash memory, but 4k is used by the bootloader. WS2812FX uses about 26k, leaving a measly 2k for the user's sketch.

In addition to REDUCED_MODES you can modify the library's WS2812FX.h file to exclude other effects from your sketch and free up some additional flash memory. If you look at ws2812fx.h, you'll see this:
```c++
#ifdef REDUCED_MODES
      _mode[FX_MODE_BREATH]                  = &WS2812FX::mode_static;
      _mode[FX_MODE_RUNNING_LIGHTS]          = &WS2812FX::mode_static;
      _mode[FX_MODE_ICU]                     = &WS2812FX::mode_static;
#else
      _mode[FX_MODE_BREATH]                  = &WS2812FX::mode_breath;
      _mode[FX_MODE_RUNNING_LIGHTS]          = &WS2812FX::mode_running_lights;
      _mode[FX_MODE_ICU]                     = &WS2812FX::mode_icu;
#endif
```
So when REDUCED_MODES is defined, the BREATH, RUNNING_LIGHTS and ICU mode functions aren't linked to your sketch. You can use the same technique to exclude other modes from your sketch. For example, you can remove the CHASE_FLASH and CHASE_FLASH_RANDOM modes by changing these two lines in WS2812FX.h:
```c++
_mode[FX_MODE_CHASE_FLASH]             = &WS2812FX::mode_static; // change to mode_static
_mode[FX_MODE_CHASE_FLASH_RANDOM]      = &WS2812FX::mode_static;
```
That will free up about 1100 bytes for your sketch to use.

**Comment by moose4lord** [comment]
This issue seems to be dead. Closing.
