### ISSUE TITLE
Flip direction 

### ISSUE THREAD

**Issue by matiasojedam** [kitesurfer1404/WS2812FX#104]
Hi

My leds are 15 led strips with 20 led each.
BUT in the setup, this are bad linked... 
effects run form top to bottom and I wish left to right...
any idea?
=(

**Comment by moose4lord** [comment]
I'm not sure I understand how your LEDs are wired. Do you have 15 strips all wired in series (electrically making one long strip of 300 LEDs) or are they wired in parallel (so all 15 strips show the same animation)?  A wiring diagram would help.

That aside, can you just turn your matrix of LEDs 90 degrees and get what you want? Or rearrange the strips so they run left to right? If neither of those options is available, then it's possible to create a translation algorithm to map from the LED arrangement you have, to the arrangement you want. Again, a wiring diagram would help to understand what we're working with.

**Comment by moose4lord** [comment]
This issue seems to be dead. Closing.
