### ISSUE TITLE
i want to edit or add some effect

### ISSUE THREAD

**Issue by LedArts** [kitesurfer1404/WS2812FX#12]
hello sir, i want to add more effects. i am using arduino but when i open auto cycle mode it doesn't show .h files how can i edit this program????

**Comment by kitesurfer1404** [comment]
The modes are stored in WS2812FX.h and WS2812FX.cpp in the main-directory. You can change them there and add more effects to the library. auto_mode_cycle.ino is only a example for using the library, not the effects itself. 
You can also add your own effects in your own code and call them from your loop-method as you would do with the Adafruit NeoPixel library without WS2812FX.

Hope this helps.

**Comment by LedArts** [comment]
yes sir it helps a lot. thank you sir

**Comment by LedArts** [comment]
i have one more question sir. where n how can i open .cpp or .h files in arduino?????

**Comment by kitesurfer1404** [comment]
I'm not sure if that is possible. You can edit them using a normal text-editor (e.g. notepad or wordpad in windows). You might want to take a look at notepad++ which is a great text editor that also highlights code etc.

**Comment by LedArts** [comment]
ok sir thank you
