### ISSUE TITLE
In-flight sync of 2 strips

### ISSUE THREAD

**Issue by scratch85** [kitesurfer1404/WS2812FX#135]
Hi,

I have a project running using 2 WS2812 strips and found this lib recently.

Is there a way to sync effects on 2 strips?

Example: With a push of a button I want to copy the current mode of strip1 to strip2.
This should be easy using something like s2.setMode(s1.getMode()).
But how about the settings, e.g. color, position of larsson scanner etc..

By the way, I am using teensy 3.2 so far and  the library works awesome!

Thanks!
scratch

**Comment by moose4lord** [comment]
getSpeed/setSpeed can be used to copy the speed parameter. It doesn't sound like you're using segments, but you can still use getColors/setColors to copy colors. 
```c++
s2.setSpeed(s1.getSpeed());
s2.setColors(0, s1.getColors(0));
```
To synchronize the two strips you'll need to reset the 'runtime' structure that is used to store the state of each strip's animation by calling the resetSegmentRuntimes() function.
```c++
s1.resetSegmentRuntimes();
s2.resetSegmentRuntimes();
```

**Comment by scratch85** [comment]
Thanks. Rather calling resetSegmentRuntimes() it should be possible to call getSegmentRuntime() and use the not yet developed setSegmentRuntime() to make a real in-flight sync, am I right?

Also I added the s2.setBrightness(s1.getBrightness()) to the above.

**Comment by moose4lord** [comment]
If you're goal is to copy one set of settings to another, it would seem easier to just do a blanket copy of the segment and runtime structures. Something like this:
```c++
    memcpy(s2.getSegments(),        s1.getSegments(),        sizeof(struct WS2812FX::Segment));
    memcpy(s2.getSegmentRuntimes(), s1.getSegmentRuntimes(), sizeof(struct WS2812FX::Segment_runtime));
```
You'd have to loop through the structures if you were using segments.

Be warned the animation state isn't always stored in the runtime structure. Sometimes the animation state is stored in the LEDs themselves. For example the Larson Scanner effect (and other effects that have a fade component) stores state in the LEDs, and uses getPixelColor() and setPixelColor() to update the animation. So I don't think you'll get a smooth transition when you copy the runtime data from one strip to another. It's always safer to run resetSegmentRuntimes().

**Comment by scratch85** [comment]
> Be warned the animation state isn't always stored in the runtime structure. Sometimes the animation state is stored in the LEDs themselves. For example the Larson Scanner effect (and other effects that have a fade component) stores state in the LEDs, and uses getPixelColor() and setPixelColor() to update the animation. So I don't think you'll get a smooth transition when you copy the runtime data from one strip to another. It's always safer to run resetSegmentRuntimes().

Tested the above code for nearly all the effects now, even Larson Scanner and it worked all the time. 
I'll check the memcpy again.

**Comment by moose4lord** [comment]
Sorry, I didn't mean to imply that the code wouldn't work, just that copying the settings from one strip to another will give you an odd partial transition for the first animation cycle (the LEDs will show half of the old effect and half of the new effect). After the first animation cycle, everything would look fine.

If you want to copy one strip's setting to another, and have the transition be instantaneous, you'd need to copy the pixel data from one strip to another too. Like so:
```c++
// num bytes copied needs to be (LED_COUNT * 3) for RGB LEDs or (LED_COUNT * 4) for RGBW LEDs
memcpy(s2.getPixels(), s1.getPixels(), LED_COUNT * 3);
```

**Comment by scratch85** [comment]
> 
> 
> Sorry, I didn't mean to imply that the code wouldn't work, just that copying the settings from one strip to another will give you an odd partial transition for the first animation cycle (the LEDs will show half of the old effect and half of the new effect). After the first animation cycle, everything would look fine.
> 
> If you want to copy one strip's setting to another, and have the transition be instantaneous, you'd need to copy the pixel data from one strip to another too. Like so:
> 
> ```c++
> // num bytes copied needs to be (LED_COUNT * 3) for RGB LEDs or (LED_COUNT * 4) for RGBW LEDs
> memcpy(s2.getPixels(), s1.getPixels(), LED_COUNT * 3);
> ```

Got it. Many thanks!
