### ISSUE TITLE
Serial_control

### ISSUE THREAD

**Issue by milezdr** [kitesurfer1404/WS2812FX#136]
Hi, I've just tried the ws2812fx and tried the serial_control example and doesnt work at all for me :( 
it only stays on the first mode static and when I try to send cmd m 5, m 8 or m n nothing happens also tried to change the brightness but that isn't working.
I'm using arduino Nano and ws2811 led strip,when I change in the example to other mods it works great but not with serial windows.
Could you know what can be the problem?
Thanks

**Comment by moose4lord** [comment]
The baud rate for the Serial comm may be set too high. The example sketch has it set to 115200, which may be too fast for your nano.
```c++
Serial.begin(115200);
```
Change the Serial.begin() call to use 9600 baud. Adding a little delay after the Serial.begin() may help too.
```c++
Serial.begin(9600);
delay(1000);
```

**Comment by milezdr** [comment]
Thanks @moose4lord but still not work.  I changed the baud rate but still no luck also tried the example with arduino uno but doesn't work 
When I send command to the arduino I see the RX led blinks but nothing happens

**Comment by moose4lord** [comment]
Strange. It works fine with my Arduino Leonardo. Is there anything displayed in the Serial Monitor window? When the sketch starts it should print several lines to the serial monitor, and any commands you type should be echoed to the serial monitor too.

**Comment by milezdr** [comment]
I tried the code on my older lap top and everything is working as it should , don't know what the problem with this maybe drivers or something.
Btw
Yes when it starts is showing in serial monitor what comand to use for brightness speed and modes
But doesnt change nothing 
Thanks anyway
