### ISSUE TITLE
LARSON scanner mode (43) crashes if SEGMENT_LENGTH=1

### ISSUE THREAD

**Issue by sprior** [kitesurfer1404/WS2812FX#145]
I realize that LARSON scanner makes no sense with just one NeoPixel, but currently setting that mode will crash the processor, all the other modes will at least not crash.

**Comment by moose4lord** [comment]
You're right. There's a divide-by-zero bug when SEGMENT_LENGTH==1. I'll fix.

Thanks for mentioning this.

**Comment by moose4lord** [comment]
Bug fixed in v1.1.7. Closing this issue.

**Comment by sprior** [comment]
Thanks for working on it!
