### ISSUE TITLE
change led count in setup() or loop()

### ISSUE THREAD

**Issue by renat2985** [kitesurfer1404/WS2812FX#15]
How I can change the led count in setup() or loop() void?
Thanks

**Comment by kitesurfer1404** [comment]
You might want to take a look at the updateLength function of the NeoPixel library.
https://github.com/adafruit/Adafruit_NeoPixel/blob/master/Adafruit_NeoPixel.h#L134
I did not test this. But it seems to be the right function to call.

**Comment by renat2985** [comment]
Not Work. 
![_134](https://cloud.githubusercontent.com/assets/1230815/23033271/1471f6f8-f480-11e6-8d63-93c271d512f0.png)

**Comment by kitesurfer1404** [comment]
You have to call it on your WS2812FX-object. Like WS2812FX.updateLength(ledCount); But with the corresponding name of the object you declared in your code.

**Comment by renat2985** [comment]
Sketch compile ok, but led number not updated.

**Comment by kitesurfer1404** [comment]
Why do you want to update the length?

**Comment by kitesurfer1404** [comment]
You might need to use the empty constructor and then call updateType and updateLength. See
https://github.com/adafruit/Adafruit_NeoPixel/blob/master/Adafruit_NeoPixel.cpp#L45
(untested).

**Comment by DarkBeardRUS** [comment]
At the beginning, when initializing an LED tape, it costs a length of 0. The change occurs during the Setup, when the sketch reads the configuration file. Then the length of the LED strip is updated.
void LightEffect :: updateLength (uint32_t  _ulc) {
   _led_count = _ulc;
   Adafruit_NeoPixel :: updateLength (_led_count);
  }
But I just increase the size of the LED strip, did not try to reduce it.

**Comment by renat2985** [comment]
@kitesurfer1404 Please add a simple change led count with setup or loop.

**Comment by MTJoker** [comment]
I have the same issue- my number of leds, the led pin and the type is read during run-time from a config file when the led object is already instantiated. So an empty constructor needs to be called on instantiation, and the parameters adjusted later. This works perfectly with the Neopixel library itself. But it does not work with yours, as your class is derived and does not provide an empty constructor. I have done an enhancement to allow this. If you want I can post a pull-request.

**Comment by kitesurfer1404** [comment]
Cool. Please do! :+1:

**Comment by MTJoker** [comment]
Unfortunately can't send pull request right now (tells me authentification failed).
Will need to figure out what's the problem... :-)

**Comment by idolpx** [comment]
I needed this ability too and added it here.

https://github.com/kitesurfer1404/WS2812FX/pull/32
