### ISSUE TITLE
What about a code with all the effects?

### ISSUE THREAD

**Issue by OURLEDS** [kitesurfer1404/WS2812FX#152]
Hey, after about 2 days of searching and almost 10 hours of trying different codes and projects ...
This is the one I consider the Roseta stonne for WS2812 ... but it is in an encrypted languaje.

Because I am just a amateur code programmer, I just can't find a way to the project I want in the time I need. 
It would be very very helpfull if the creator or another person that understand this library explain me or share a code where it is used all of the effects, and I just need to change the times, speed and order of sequences,.
I know how to make loops and perhaps even insert some buttons and other things, but defientely I don't know how to write the effects to appear in the ws2812 ring.
This is the only code I found and I managed to change jsut to make something simialr to 1 of the aniamtions I need, but is just a very bad use of the whole library potential.

[<script src="https://gist.github.com/OURLEDS/075f47561375671c51d3b7dc0c836cf8.js"></script>](url)

**Comment by OURLEDS** [comment]
Just to let readers know what I am looking for, it is something like the min 4:10 of this video
https://www.youtube.com/watch?v=4fzjkswrgDs

**Comment by moose4lord** [comment]
I'm not exactly sure what your goal is. It seems like you're interested in cycling through your own list of custom effects, which really isn't the WS2812FX libs forte. To cycle through effects, where each effect has independent parameters (i.e. duration, brightness, speed, colors, options), you can look at the ws2812fx_patterns_web sketch in the examples folder. Strip out all the web interface stuff and just hardcode the patterns array with the effects you like:
For example, replace this:
```c++
Pattern patterns[MAX_NUM_PATTERNS] = { DEFAULT_PATTERN };
int numPatterns = 1;
```
with this:
```c++
// duration, brightness, numSegments, [ { first, last, speed, mode, options, colors[] } ]
Pattern patterns[MAX_NUM_PATTERNS] = {
  {30, 64, 1, { {0, numLeds-1, 1000, FX_MODE_FADE, NO_OPTIONS, {RED,  BLACK, BLACK}} }},
  {30,128, 1, { {0, numLeds-1, 2000, FX_MODE_SCAN, NO_OPTIONS, {BLUE, BLACK, BLACK}} }},
  {30,255, 1, { {0, numLeds-1, 2000, FX_MODE_BLINK,NO_OPTIONS, {GREEN,BLACK, BLACK}} }}
};
int numPatterns = 3;
```

Creating custom effects is a different animal. The User Guide has some info about creating a custom effect and as you've found, there's a couple good example sketches dealing with custom effects. But honestly, it's not trivial and probably not something a novice programmer can just dive into. I'd stick with the built-in effects and the handful of custom effects in the src/custom folder while you're still learning to use the lib.

**Comment by OURLEDS** [comment]
Thanks for the reply;
Yes probably I will end up learning everything from scratch as what I want is very simple but very specific.
In the sencond answer you can see some example videos attached, where you can see the kind of aniamtion I am looking for, but I just simple don't know how to even start, as many of them will requiere of many if, for, voids and creating paramerrter and variables that I am not even remotely used to work with.
So probably if at elast someone guide me to a palce where can I start learning the basic of Arduino code creating for LEDS? if that even exist.

**Comment by kitesurfer1404** [comment]
Take a look at https://github.com/scottkildall/NeoPixel-Samples
There are some basic examples. My advice would be: try them, modify them, see what happens. Start with neopixel_basic. Try to understand what each line does. Try to modify the code, so only one half lights up. Try to modify the code, so the first half lights up red, the second half blue. Find more ideas to implement and try try try. ;-)
Move on to neopixel_3color and play with it. Move on to neopixel_moving1 and try to modify the code, so the animation runs backwards. Implement 4 segments. Implement one static segment and one moving. Implement, that the static segment grows every time the moving segment starts from the beginning... At that point you will get very near to some of your effects from the videos. ;-)
Also: create a repository where you check in your code and link your progress here. I would be happy to see you also sharing your learning experience and was to solve the problem. I promise: there is a high hurdle only at the beginning. Overcome that and you will get to the point where you create your own effects very soon.

**Comment by kitesurfer1404** [comment]
Also: use the built in examples of Arduino. Read and understand the code line by line. Modify small parts, see what happens. 
--> Do small steps you can manage. Break down your ideas into small code segments that can be understood, tested and used again later.

**Comment by OURLEDS** [comment]
Look my main issues are the kind like this:

I have this simple code running:
https://gist.github.com/OURLEDS/22f613b3b8374fc32e7d05d855012453
Which awesome, but I can't control nothing

So I just went to all the file of this library and I found codes like this:

https://gist.github.com/OURLEDS/cb9b674359e3f55785855d94756cc689
It is what I wanted, a effect with options to customize ... but how I add it to a simple new file code from scratch?

Thanks

**Comment by moose4lord** [comment]
Look at the ws2812fx_custom_effect2 sketch in the examples folder. It shows how to use the custom effects found in the src/custom folder.

**Comment by OURLEDS** [comment]
> 
> 
> Look at the ws2812fx_custom_effect2 sketch in the examples folder. It shows how to use the custom effects found in the src/custom folder.

It doesn't explain, each effect has a different way of code writing it with the unit 8, 16 or 32...
it requieres intermediater advanced code knoweldege I asm afraid

**Comment by moose4lord** [comment]
You're right, the effects code can be quite difficult. @kitesurfer1404 mentions some nice tutorials (NeoPixel-Samples, see above) for novice software developers that want to work with NeoPixels. You should start there.
