### ISSUE TITLE
I lack the three functions in your library.

### ISSUE THREAD

**Issue by DarkBeardRUS** [kitesurfer1404/WS2812FX#16]
I lack the three functions in your library.
1. Shifting the effect starts from the beginning of the tape
2. insert effect certain additional effect it.
3. Ability to share software on the tape 2, and let them alone effect it (should work with paragraph 1)

**Comment by kitesurfer1404** [comment]
Sounds usefull. I have a rough idea how to add these functions, I guess. I'll try to figure that out. Maybe not 1., but a feature that solves 3. and can be used to "shift" the effect.
