### ISSUE TITLE
Wrong colors

### ISSUE THREAD

**Issue by kylix34** [kitesurfer1404/WS2812FX#160]
I have a WS2812B LED strip (3 wires: V+, DATA and GND) and it's not displaying the correct colors.
I tried all the possible combinations: NEO_RGB, NEO_RBG, NEO_GRB, NEO_GBR, NEO_BRG, NEO_BGR but the colors are still inverted....
The example I'm using is esp8266_webinterface

**Comment by moose4lord** [comment]
Does it still show the wrong colors with a simple sketch like this:
```c++
#include <WS2812FX.h>

#define LED_COUNT 30
#define LED_PIN D1

WS2812FX ws2812fx = WS2812FX(LED_COUNT, LED_PIN, NEO_GRB + NEO_KHZ800);

void setup() {
  ws2812fx.init();
  ws2812fx.setBrightness(100);
  ws2812fx.setSpeed(1000);
  ws2812fx.setColor(RED); // or GREEN or BLUE
  ws2812fx.setMode(FX_MODE_STATIC);
  ws2812fx.start();
}

void loop() {
  ws2812fx.service();
}
```

**Comment by kylix34** [comment]
Your simple sketch worked. After that I loaded again the full sketch and the colors are loading almost OK. It's the color picker on the webpage that it's not very accurate. Thanks!

**Comment by kitesurfer1404** [comment]
Do all recent mobile phone support the HTML-color-input-tag?
`<input name="fx_color" type="color" value="#ff0000">`
Then we can maybe upgrade the code to use the systems colorpicker which might be more reliable.

**Comment by kylix34** [comment]
The color palette template used here: https://github.com/jasoncoon/esp8266-fastled-webserver/blob/master/data/index.htm, works on my phone (that project uses the FastLED library)

**Comment by debsahu** [comment]
I use [iro.js](https://iro.js.org) works flawlessly on Android, iOS and chrome on PC.
