### ISSUE TITLE
Individual light control

### ISSUE THREAD

**Issue by smackflad** [kitesurfer1404/WS2812FX#170]
Is it possible to control a specific led from an LED strip with the WS2812FX library? 
For example evey led is off except the first one.

**Comment by kitesurfer1404** [comment]
Yes. The same way, you would use the Adafruit NeoPixel library: ws2812fx.setPixelColor(0, 255, 120, 36) with 0 being the first pixel, 255, 120, 36 being the RGB-values of the pixel to set.
