### ISSUE TITLE
Brightness per segment

### ISSUE THREAD

**Issue by somebuddy87** [kitesurfer1404/WS2812FX#171]
Hi,

Is it possible to add the segment_brightness as parameter of the setSegment function?

Thank you

**Comment by moose4lord** [comment]
Sadly, no. Brightness is implemented in the Adafruit_NeoPixel library, upon which WS2812FX is built, and affects the brightness of the entire strip of LEDs.

I suppose you could use the setColor() and setColors() functions to dynamically adjust a segment's colors and so their brightness.
```c++
setColor(uint8_t seg, uint32_t c);
setColors(uint8_t seg, uint32_t* c);
```
Other "hardcoded" effect colors, like rainbow effects, cannot be adjusted per segment.

**Comment by dmak** [comment]
Would it be possible to add support of several LED strips to the library (each strip is connected to it's own data pin)? Than the brightness of each strip can be controlled individually.

**Comment by moose4lord** [comment]
The lib already supports multiple strips on different GPIO pins. All strips are programmed independently. See #165
