### ISSUE TITLE
Is it possible to add to Home Assistant?

### ISSUE THREAD

**Issue by vitinhosessa** [kitesurfer1404/WS2812FX#173]
I wish to add to Home Assistant.

**Comment by JulianS-Uni** [comment]
Can you explain what you mean a little further?

**Comment by vitinhosessa** [comment]
Can i control with MQTT?

**Comment by JulianS-Uni** [comment]
Probably not, probably yes. WS2812FX is a library that lets you control your LEDs only. In the Examples folder are some examples how to control them with Wifi or over Serial. But when you want to use MQTT and know the topics your MQTT server publishes you can write the MQTT client part by yourself with [PubSubClient](https://github.com/knolleary/pubsubclient).
[Here](https://randomnerdtutorials.com/esp32-mqtt-publish-subscribe-arduino-ide/) are some more examples how to use it.
