### ISSUE TITLE
plz can you add off/on button, google voice assistant and last music control

### ISSUE THREAD

**Issue by deppen12** [kitesurfer1404/WS2812FX#174]
hi 

plz add offf/on button. there must be a button to control it

can you add this google voice assistant (https://community.blynk.cc/t/voice-controlled-led-strip-with-google-assistant-ifttt-and-blynk/18234) 

and last can you add some function like this ( https://www.youtube.com/watch?v=w_an42u0bq8 ) or ( https://www.youtube.com/watch?v=fPK4K9sv6tI )

**Comment by moose4lord** [comment]
This enhancement request doesn't seem to be going anywhere, so I'm closing. Feel free to reopen if someone wants to work on it.
