### ISSUE TITLE
Accessing "real" brightness level vs. rewriting "breath" and "fade" modes

### ISSUE THREAD

**Issue by aj-gh** [kitesurfer1404/WS2812FX#18]
For a specific project I'd need to access the currently set LED brightness level.
This would work fine with "getBrightness" for most effects but doesn't work when using the "breath" or "fade" effects because these effects seem to set the Neopixel libraries brightness level themselves which has no relation to the overall brightness setting (limit) which is returned by "getBrightness".

Unfortunately this library replaces the "getBrightness" function of the Neopixel library so I had to patch my version and add a "getRealBrightness" function to return the currently set brightness value.

While this is one possible solution the other would be to avoid changing the "upstream" brightness level and adjust the brightness level in both the "breath" and "fade" modes by changing the pixel colors to the proper brightness-adjusted values, similar to what is being done for example in the "twinkle fade" mode among others. This would also avoid some brightness-flickering that currently seems to occur when adjusting the brightness level (limit) while running those two modes as the change causes an immediate brightness change until the effect triggers again and sets the proper effect-matching brightness.

For the first described solution ("getRealBrightness") I could submit a pull request. However I do think the second solution might be a better approach.

**Comment by kitesurfer1404** [comment]
I understand and will implement this, hopefully soon. Will correct the effects instead of overwriting the getBrightness function with different results.
I put this on my todo list. Please be patient. Thanks for your input!
