### ISSUE TITLE
ESP32_RMT_Driver.h: No such file or directory

### ISSUE THREAD

**Issue by Edris89** [kitesurfer1404/WS2812FX#181]
Hi there I am trying to compile your esp32 example
but it seems that it doesn't let me do that

Getting the following error
```
ESP32_RMT_Driver.h: No such file or directory
```

**Comment by moose4lord** [comment]
The ESP32_RMT_Driver.h file is included in the examples/ws2812fx_esp32 folder. Did you forget to copy it along with the ws2812fx_esp32.ino file?
