### ISSUE TITLE
How to add Custom effect on top of the implemented effect?

### ISSUE THREAD

**Issue by Skybeat** [kitesurfer1404/WS2812FX#195]
Hello,

may I missunderstand the examples but for me it looks like the examples shows only the custome effect.
What i want to do is:
- add a custome effect e.g. in slot 1 of the custome effects
- add a custome effect e.g. in slot 2 of the custome effects
and all on top of the implemented effects, so that i can switch between the implemented effects and the custome effect.

I have already my sketch with two buttons, forward and backward of effects, but i dont understand how to add custom effects in particular  slots.
May you can provide a short example what shows how to do this.

Thank you
Nico

**Comment by moose4lord** [comment]
Hi Nico, you'll need to #include up to four custom modes at the top of your sketch:
```c++
#include "custom/DualLarson.h"
#include "custom/Popcorn.h"
#include "custom/RainbowFireworks.h"
#include "custom/TriFade.h"
```
Then include calls to setCustomMode() in the setup() function:
```c++
  uint8_t dualLarsonMode  = ws2812fx.setCustomMode(F("Dual Larson"), dualLarson);
  uint8_t popcornMode  = ws2812fx.setCustomMode(F("Popcorn"), popcorn);
  uint8_t rainbowFireworksMode  = ws2812fx.setCustomMode(F("Rainbow Fireworks"), rainbowFireworks);
  uint8_t triFadeMode  = ws2812fx.setCustomMode(F("Tri Fade"), triFade);
```
The effects are added in the order the setCustomMode() functions are executed, so in this example the "dualLarson" custom effect would be in slot 1, "popcorn" would be in slot 2, etc. 

The custom mode is assigned to a segment like so:
```c++
ws2812fx.setSegment(0,  0,  LED_COUNT-1, dualLarsonMode, RED, 1000, NO_OPTIONS);
```
