### ISSUE TITLE
How does fadeOut work?

### ISSUE THREAD

**Issue by dunklesToast** [kitesurfer1404/WS2812FX#214]
The fadeOut function is referenced here:
https://github.com/kitesurfer1404/WS2812FX/blob/abece9a2a5a23027243851767c55cb8d2e19ff05/src/WS2812FX.h#L423

When I want to use it, Arduino IDE says that the class WS2812FX has no member named 'fadeOut'. Is this a deprecated feature? If not, how to use it?

**Comment by kitesurfer1404** [comment]
Try fade_out, not fadeOut.

**Comment by dunklesToast** [comment]
Oh my fault. Now it works. Thanks!
I think fade_out is missing in the keywords.txt. It's not being highlighted in the editor.
