### ISSUE TITLE
Animation cycle

### ISSUE THREAD

**Issue by craigrobbo** [kitesurfer1404/WS2812FX#233]
Hi again

Sorry I know you proberbly shudder when you see me crop up

Im making greathead way with my code.

In the CPP file I am wondering if its possible to make an edit so that effects like Color wipe do not continue their cycle but instead would just complete one cycle only?

For example with color wipe all LED would light up one after the other, then they would turn off one after the other...then would just stay off?

Thank you :)

**Comment by moose4lord** [comment]
You're looking for the isCycle() function. It returns "true" when an animation has completed one cycle. It is discussed in issue #199.

Something like this
```c++
void loop() {
  ws2812fx.service();

  if(ws2812fx.isCycle()) { // test if animation cycle is complete
    ws2812fx.stop();
  }
}
```

**Comment by craigrobbo** [comment]
> 
> 
> You're looking for the isCycle() function. It returns "true" when an animation has completed one cycle. It is discussed in issue #199.
> 
> Something like this
> 
> ```c++
> void loop() {
>   ws2812fx.service();
> 
>   if(ws2812fx.isCycle()) { // test if animation cycle is complete
>     ws2812fx.stop();
>   }
> }
> ```

Thanks Keith.

I was thinking more is it possible to permenantly edit the Library CPP file so that the Color wipe animation never  repeats and/or so it only compleates half of its cycle?

**Comment by moose4lord** [comment]
It's possible, but that's not something I want to get into. Sorry.

**Comment by craigrobbo** [comment]
no worries mate thank you :)
