### ISSUE TITLE
Changed Delay in mode_static

### ISSUE THREAD

**Issue by edsmskinner** [kitesurfer1404/WS2812FX#247]
I was seeing a delay in rendering the LEDs from when the segment was set to when the LED's actually rendered.  I traced it down to the mode_static function returning 500 causing a 500 millisecond retry cycle.  I changed my version to 100 and the delay went away.  My question is... 
1. Will this cause any issues?
2. Why was it set to 500?  I am sure there was a reason just wanted to be sure I understood any repercussions of setting this to 100.
Also, totally awesome library!!!!!   I sincerely appreciate your work and awesome library.
Thanks!
Ed

**Comment by moose4lord** [comment]
In WS2812FX v1.2.4 the delay for mode_static was changed from a hardcoded 500ms to whatever "speed" is set in the setSpeed() or setSegment() functions. So you shouldn't need to patch the lib code, just set the segment speed.
