### ISSUE TITLE
esp8622 random flicker

### ISSUE THREAD

**Issue by wchpikus** [kitesurfer1404/WS2812FX#248]
esp8622, random led flick.
simple scratch working ok, but with wifi and web server flick.

**Comment by moose4lord** [comment]
Are you using the esp8266_webinterface example sketch? How many LEDs in your strip? Have you looked at the [Adafruit NeoPixel Uber Guide](https://learn.adafruit.com/adafruit-neopixel-uberguide) and adhered to their best practices?
