### ISSUE TITLE
Syncing via frames?

### ISSUE THREAD

**Issue by buges** [kitesurfer1404/WS2812FX#254]
Hi

I Have a question (sorry if this is obvious but i've just started learning C++/Arduino)

On the master Arduino I've used the .isFrame to output the frame numbers and send them over wifi, this is working fine and i am seeing the frame numbers on the slave Arduino.

How can I use the incoming frame numbers to trigger the led strip so it stays in time with the master Arduino  

Thanks

**Comment by moose4lord** [comment]
There's a trigger() function which forces a step to the next animation frame. See the external_trigger example sketch.

**Comment by buges** [comment]
Thanks
