### ISSUE TITLE
Esp8266 MQTT Problem

### ISSUE THREAD

**Issue by AxellentAlex** [kitesurfer1404/WS2812FX#263]
Hi, I bought a D1 Mini (Esp8266) and connected it to my Led Strip (ws2812b). I added the WS2812FX library and tested the Example "auto_mode_cycle" and everything works fine but if I add it to my Mqtt Project, so I can controll the Leds with OpenHab no Effect works as it should execpt Static. (https://pastebin.com/r91DDaAJ).

**Comment by moose4lord** [comment]
In your loop() function you're constantly calling setMode(), which resets all the animation parameters. You should only call setMode() when the mode changes.

**Comment by AxellentAlex** [comment]
Thanks. I added an update check and that fixed it
