### ISSUE TITLE
Create a new WS2812FX Object for new led settings

### ISSUE THREAD

**Issue by Miky94x** [kitesurfer1404/WS2812FX#264]
Hi, is possible to create a new WS2812FX object at runtime?

i've tried this way, when i receive serial data, using a switch case i select between two or more led configuration but the strip respond only at the first ws2812fx object change with some problem (some blink random), on the second try the arduino don't respond to the serial and all the leds turn off

code: [Pastebin](https://pastebin.com/GzH3qFYD)

is possible to change the led type at runtime?
thanks

**Comment by moose4lord** [comment]
The Adafruit_Neopixel lib provides the updateType() function to change the LED type. Something like this:
```c++
ws2812fx.updateType(NEO_GRB + NEO_KHZ800);
```

**Comment by Miky94x** [comment]
I've read all the neopixel function but as i see without the needed attention
Thanks and have a good day
