### ISSUE TITLE
Is there anyway we can connect it to alexa and control through voice ?

### ISSUE THREAD

**Issue by Spin5123** [kitesurfer1404/WS2812FX#270]
I made the webserver and now want to control it through alexa if possible and maybe have option of both the webserver and alexa if its alexa ill maybe just use it for the rainbow effect ,color, brightness, turning it off and on

**Comment by moose4lord** [comment]
See the **ws2812fx_alexa** example sketch.

**Comment by Spin5123** [comment]
I'm very new to this and basically have no knowledge I'll give it a look and maybe come back here
