### ISSUE TITLE
esp8266 web interface issue with data pin

### ISSUE THREAD

**Issue by buchsg** [kitesurfer1404/WS2812FX#271]
hello,
I'm facing an issue with my esp8266 eps-01 and the web interface, to get it to work i need to unplug the data wire, powering up the esp and only then plug the data wire back... What i am doing wrong ?

**Comment by moose4lord** [comment]
Sounds like you're using GPIO0 to drive your LEDs. GPIO0 has special requirements during the ESP's boot phase, so you should avoid using it. Try using GPIO2 to drive your LEDs.
