### ISSUE TITLE
Just show 2 color

### ISSUE THREAD

**Issue by olieter** [kitesurfer1404/WS2812FX#275]
When is choose this code its shows just the 2 first color the thirt dont show it 

setSegment() also allows you to specify up to three colors using this syntax:

uint32_t colors[] = {RED, GREEN, BLUE}; // create an array of colors
ws2812fx.setSegment(0, 0, LED_COUNT-1, FX_MODE_BLINK, colors, 2000, false);

**Comment by moose4lord** [comment]
Not all modes use three colors. Actually, of the standard effects, only the TRICOLOR_CHASE and BICOLOR_CHASE modes use three colors. BLINK mode only uses two. The custom TRIFADE mode uses three colors and may give you the effect you're looking for.
