### ISSUE TITLE
cannot convert 'const char*' to 'const__FlashStringHelper*' in return

### ISSUE THREAD

**Issue by theredore** [kitesurfer1404/WS2812FX#276]
I seem to be having a problem with them on the arduino nano every:
cannot convert 'const char*' to 'const__FlashStringHelper*' in return
this is using your autochange example which has worked on all my other boards just fine
this was the output:
`/home/builder/opt/arduino-builder/arduino-builder -compile -core-api-version 10611 -hardware /home/builder/opt/arduino-builder/hardware -hardware /home/builder/.arduino15/packages -tools /home/builder/opt/arduino-builder/tools -tools /home/builder/.arduino15/packages -built-in-libraries /home/builder/opt/libraries/latest -logger humantags -fqbn arduino:megaavr:nona4809:mode=on -build-cache /tmp -build-path /tmp/105318084/build -verbose -prefs runtime.tools.arduinoOTA.path=/home/builder/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -prefs runtime.tools.avr-gcc.path=/home/builder/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5 -prefs runtime.tools.avrdude.path=/home/builder/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17 -prefs runtime.tools.arduino101load.path=/home/builder/.arduino15/packages/Intel/tools/arduino101load/2.0.1 -prefs runtime.tools.serial-discovery.path=/home/builder/.arduino15/packages/builtin/tools/serial-discovery/1.1.0 -prefs runtime.tools.dfu-util.path=/home/builder/.arduino15/packages/arduino/tools/dfu-util/0.9.0-arduino2 -prefs runtime.tools.core2-32-poky-linux.path=/home/builder/.arduino15/packages/Intel/tools/core2-32-poky-linux/1.6.2+1.0 -prefs runtime.tools.flashpack.path=/home/builder/.arduino15/packages/Intel/tools/flashpack/2.0.0 -prefs runtime.tools.openocd.path=/home/builder/.arduino15/packages/arduino/tools/openocd/0.10.0-arduino9 -prefs runtime.tools.nrf5x-cl-tools.path=/home/builder/.arduino15/packages/arduino/tools/nrf5x-cl-tools/9.3.1 -prefs runtime.tools.i586-poky-linux-uclibc.path=/home/builder/.arduino15/packages/Intel/tools/i586-poky-linux-uclibc/1.6.2+1.0 -prefs runtime.tools.sketchUploader.path=/home/builder/.arduino15/packages/Intel/tools/sketchUploader/1.6.2+1.0 -prefs runtime.tools.arc-elf32.path=/home/builder/.arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1 -prefs runtime.tools.ctags.path=/home/builder/.arduino15/packages/builtin/tools/ctags/5.8-arduino11 -prefs runtime.tools.linuxuploader.path=/home/builder/.arduino15/packages/arduino/tools/linuxuploader/1.5.1 -prefs runtime.tools.esptool.path=/home/builder/.arduino15/packages/esp8266/tools/esptool/2.5.0-3-20ed2b9 -prefs runtime.tools.arm-linux-gcc.path=/home/builder/.arduino15/packages/arduino/tools/arm-linux-gcc/4.9.3 -prefs runtime.tools.bossac.path=/home/builder/.arduino15/packages/industruino/tools/bossac/1.7.0-industruino -prefs runtime.tools.CMSIS.path=/home/builder/.arduino15/packages/arduino/tools/CMSIS/4.5.0 -prefs runtime.tools.x86-linux-gcc.path=/home/builder/.arduino15/packages/arduino/tools/x86-linux-gcc/7.2.0 -prefs runtime.tools.CMSIS-Atmel.path=/home/builder/.arduino15/packages/arduino/tools/CMSIS-Atmel/1.2.0 -prefs runtime.tools.arm-none-eabi-gcc.path=/home/builder/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4 -prefs runtime.tools.mkspiffs.path=/home/builder/.arduino15/packages/esp8266/tools/mkspiffs/2.5.0-3-20ed2b9 -prefs runtime.tools.xtensa-lx106-elf-gcc.path=/home/builder/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9 -libraries /tmp/105318084/custom -libraries /tmp/105318084/pinned /tmp/105318084/auto_mode_cycle_copy2

Multiple libraries were found for "Adafruit_NeoPixel.h"

Used: /home/builder/opt/libraries/latest/adafruit_neopixel_1_7_0

Not used: /home/builder/opt/libraries/latest/pinduino_1_5_0

Not used: /home/builder/opt/libraries/latest/leaphy_extra_extension_0_0_6

Using library ws2812fx_1_3_1 at version 1.3.1 in folder: /home/builder/opt/libraries/latest/ws2812fx_1_3_1

Using library adafruit_neopixel_1_7_0 at version 1.7.0 in folder: /home/builder/opt/libraries/latest/adafruit_neopixel_1_7_0

In file included from /home/builder/opt/libraries/latest/adafruit_neopixel_1_7_0/Adafruit_NeoPixel.h:41:0,

from /home/builder/opt/libraries/latest/ws2812fx_1_3_1/src/WS2812FX.h:42,

from /home/builder/opt/libraries/latest/ws2812fx_1_3_1/src/WS2812FX.cpp:55:

/home/builder/opt/libraries/latest/ws2812fx_1_3_1/src/WS2812FX.cpp: In member function 'const __FlashStringHelper* WS2812FX::getModeName(uint8_t)':

/home/builder/.arduino15/packages/arduino/hardware/megaavr/1.8.5/cores/arduino/Arduino.h:30:20: error: cannot convert 'const char*' to 'const __FlashStringHelper*' in return

#define F(str) (str)

^

/home/builder/opt/libraries/latest/ws2812fx_1_3_1/src/WS2812FX.cpp:377:12: note: in expansion of macro 'F'

return F("");

^

exit status 1`

**Comment by moose4lord** [comment]
I compiled the auto_mode_cycle sketch for the Nano Every with no problems. The latest version of the Nano Every board package is v1.8.7. You might try installing that and see if it helps.

**Comment by theredore** [comment]
Thank you,
For some reason it only wanted to upload the code through the ide and
didn't work through the web editor for some reason.
