### ISSUE TITLE
Port from Adafruit_NeoPixel to WS2812Serial for Teensy

### ISSUE THREAD

**Issue by mkalkbrenner** [kitesurfer1404/WS2812FX#277]
FYI I did an experimental port from Adafruit_NeoPixel to the non blocking WS2812Serial library for Teensy:
https://github.com/mkalkbrenner/WS2812FX/tree/WS2812Serial

It is not heavily tested yet, but feedback is welcome.

**Comment by moose4lord** [comment]
I have added a ws2812fx_teensy example sketch, which uses a custom show() function to use Paul Stoffregen's [WS2812Serial](https://github.com/PaulStoffregen/WS2812Serial) lib for the Teensy. Thanks for the inspiration.
