### ISSUE TITLE
Ambibox or similar compatibility

### ISSUE THREAD

**Issue by xjustbmw** [kitesurfer1404/WS2812FX#281]
Can we use this over wifi or lan to use ambibox or similar software? 
Map the edges of the content of pc to the led strips.

I am now using an additional raspberry pi to map a virtual usb port. Pc is far away and only hdmi connection is present.

**Comment by moose4lord** [comment]
The WS2812FX lib doesn't support what you're asking about. The FastLED lib may work. See this DIY tutorial:
[https://imgur.com/a/7jRhp#efGu0fC](https://imgur.com/a/7jRhp#efGu0fC).
