### ISSUE TITLE
Dumb question - is there a simple setPixelColor function?

### ISSUE THREAD

**Issue by IraSch** [kitesurfer1404/WS2812FX#282]
I really like this library to use with ESP32 - very straightforward and simple.

But a dumb question - is there a function similar to 

` strip.setPixelColor(2, strip.Color(0, 0, 255));`
  
to just set a neopixel to a specific color - no special effects, just simple pixel commands for ESP32

Thanks.

**Comment by kitesurfer1404** [comment]
Yes, you can use the setPixelColor function from the Adafruit NeoPixel library. Just stop all effects, so they don't overwrite your manually set pixels. Or do I get something wrong here?

**Comment by IraSch** [comment]
Yes, that was my question. I wanted to confirm that the regular neopixel function could be used before starting to use your library. Your library seems much "cleaner" than alternatives when it comes to running on ESP32. Thank you.
