### ISSUE TITLE
Static mode very slow color update

### ISSUE THREAD

**Issue by silardg** [kitesurfer1404/WS2812FX#286]
I'm running the service in a separate task.
When I change the main color that the static uses, it takes about 4-5 seconds till it updates.
How can I "force a color check"?

**Comment by moose4lord** [comment]
In the case of the static effect, the speed parameter sets how often the color is updated. If speed=100, then the color will be updated every 100ms.

```c++
ws2812fx.setSpeed(100);
```

**Comment by silardg** [comment]
I'll try and report back. Thanks for the fast reply.

**Comment by silardg** [comment]
Still very slow, is there some force function?

**Comment by moose4lord** [comment]
Although you shouldn't need to, you can force the LEDs to update by calling the trigger() function.
```c++
ws2812fx.trigger();
```
