### ISSUE TITLE
merge effects (back) with wled

### ISSUE THREAD

**Issue by WiredLife** [kitesurfer1404/WS2812FX#290]
Can anyone please merge the additional effects from wled back to ws2812fx?
https://github.com/Aircoookie/WLED/blob/master/wled00/FX.cpp
would be very very kind <3

**Comment by moose4lord** [comment]
Since this seems to not be getting a lot of traction, I'm going to close this issue. I agree WLED has a lot of nice effects, but porting them back to WS2812FX would be a big task.
