### ISSUE TITLE
Connecting 2 or more esp8266 modules on the same Web Interface

### ISSUE THREAD

**Issue by stelios-stavropoulos** [kitesurfer1404/WS2812FX#296]
Hi! I made 2 identical builds using the esp8266_webinterface example because I wanted to have my led strips far from one another. I thought by putting the same static ip to both esp8266 modules it would control them both but when I plug them only one communicates with the web interface. And if I unplug it then the other works fine. I searched it on the internet and it probably is "ip conflict". Does anyone have an idea how to control them both from my phone simultaneously? Thanks in advance!!!

**Comment by moose4lord** [comment]
There's no way to simultaneously config two different ESP8266s using the esp8266_webinterface sketch. However, you can assign different IP addresses to each ESP8266, then open up two tabs in your browser with the respective IP addresses. Each browser tab controls one ESP.

Alternately, if you have an Android phone, you can upload the ws2812fx_patterns_web example sketch to your ESPs and use the [LEDfx](https://play.google.com/store/apps/details?id=com.champlainsystems.ledfx&hl=en_US&gl=US) app from the Google Play store to control your lights.

**Comment by stelios-stavropoulos** [comment]
OK IT ALL WORKED!!!! Thank you so much!!!
