### ISSUE TITLE
Http controll

### ISSUE THREAD

**Issue by pettib** [kitesurfer1404/WS2812FX#3]
I really like your project.
But I wounder if there are any possibility to control it from external webpage with post och get function.
I´m don´t have the knowledge to figure it out.
I want to control it from a Vera home automation controller. 
Thanks.

**Comment by kitesurfer1404** [comment]
Thanks!

Yes, you can control the ESP8266 example with simple http-gets:

`http://<yourESP>/set?m=<mode_no>`  **set mode to <mode_no>**
`http://<yourESP>/set?b=+` **increase brightness by BRIGHTNESS_STEP steps**
`http://<yourESP>/set?b=-` **decrease brightness by BRIGHTNESS_STEP steps**
`http://<yourESP>/set?s=+` **increase speed by SPEED_STEP steps**
`http://<yourESP>/set?s=-` **decrease speed by SPEED_STEP steps**

BRIGHTNESS_STEP (default 15) and SPEED_STEP (default 10) are defined in line 73/74 of esp8266_webinterface.ino

To get all modes as html-list-items (`<li>...</li>`):
`http://<yourESP>/modes`

I hope this helps.

**Comment by pettib** [comment]
Thanks. :-)
