### ISSUE TITLE
MSGEQ7 support

### ISSUE THREAD

**Issue by marksev1** [kitesurfer1404/WS2812FX#30]
For "music visualisation"/ "spectrum analyzer" effects, the MSGEQ7 is a great chip, there are quite a few examples on youtube. It would make your library more complete if you would support it.

**Comment by kitesurfer1404** [comment]
I just ordered some off ebay from china. Will take a look at this at some point. I guess this could be a different lib in it's own. WS2812FX.music or so.

**Comment by moose4lord** [comment]
Closing this issue. See the examples/ws2812fx_msgeq7 sketch for a demo of using ws2812fx with msgeq7 module.
