### ISSUE TITLE
Any chance that we can count animations on specific segments?

### ISSUE THREAD

**Issue by StefanMeGit** [kitesurfer1404/WS2812FX#309]
I tried to set all the segments to white via:

`ws2812fx.setSegment(0, firstLED, lastLED, FX_MODE_STATIC, PURPLE, 500, NO_OPTIONS);`

then a activate another segment to an animation:

`ws2812fx.setSegment(1, firstLED, lastLED, FX_MODE_RAINBOW, COLORS, 500, NO_OPTIONS);`

But `ws2812fx.isCycle()` counts for every segment including segment 1, which is active all the time... is it possible to just get information when segement 1 is finished the animation?

**Comment by moose4lord** [comment]
The isCycle() function has two signatures:
```c++
bool WS2812FX::isCycle();
bool WS2812FX::isCycle(uint8_t seg);
```
You can use the second form and pass in the segment number to get the animation cycle status of a specific segment.
