### ISSUE TITLE
Will This Work With RGBW NeoPixels Too?

### ISSUE THREAD

**Issue by 1CM69** [kitesurfer1404/WS2812FX#318]
Been using the standard NeoPixels lib with LEDs set as NEO_WGRB but stumbled across your code which looks really interesting. 

Will yours work with the RGBW LEDs too?

**Comment by moose4lord** [comment]
Yes, WS12812FX is compatible with RGBW LEDs. When you set a color parameter, set the most-significant byte to the white LED intensity, just like the Adafruit_Neopixel library.

**Comment by 1CM69** [comment]
> Yes, WS12812FX is compatible with RGBW LEDs. When you set a color parameter, set the most-significant byte to the white LED intensity, just like the Adafruit_Neopixel library.

Great, thanks.
