### ISSUE TITLE
Overlay, 2 effects with different start modes

### ISSUE THREAD

**Issue by buges** [kitesurfer1404/WS2812FX#319]
After having a look at the overlay example, is there any way to start one virtual effect normally ws2812fx.start();
and the other using ws2812fx.trigger(); ?

Thanks

**Comment by moose4lord** [comment]
I tried it and it seems to work fine. Attached is my test sketch.

[ws2812fx_overlay_with_trigger.zip](https://github.com/kitesurfer1404/WS2812FX/files/9527624/ws2812fx_overlay_with_trigger.zip)

**Comment by buges** [comment]
Perfect, Thank you very much.
