### ISSUE TITLE
Make a segment not in order?

### ISSUE THREAD

**Issue by eliteAnorak** [kitesurfer1404/WS2812FX#320]
I rarely make posts here on GitHub, so apologies if this isn't the right place for this question. 

I'm trying to make a segment of LEDs, but because of how it was laid out in my project I have to make the segment (6,7,2,8,9) instead of (6,7,8,9,10). Is this possible using this library?

Thanks!

**Comment by moose4lord** [comment]
This issue of managing LEDs that are not wired sequentially comes up every once in a while. It is discussed at the beginning of issue #284. The solution is to create a virtual LED strip (to run the effect), and a physical strip along with a customShow() function (to map virtual LEDs to physical LEDs). Please see issue #284 for an example sketch.
