### ISSUE TITLE
Adafruit Neopixel broke ESP8266

### ISSUE THREAD

**Issue by Jens869** [kitesurfer1404/WS2812FX#321]
the Adafruit Neopixel support for ESP8266 is broken. It's probably due to the ESP8266 3.0 board support.
This means that all examples based on Adafruit Neopixel no longer work either.
Not even the sample scripts from Adafruit.

**Comment by moose4lord** [comment]
I could not reproduce this issue. Compiling worked fine for me with the latest Adafruit_Neopixel lib. I left a comment on the issue you created on the Adafruit_Neopixel Github page.

**Comment by Jens869** [comment]
Library directory deleted and created again
