### ISSUE TITLE
How to reverse the led order?

### ISSUE THREAD

**Issue by biccius** [kitesurfer1404/WS2812FX#329]
Hello everyone.
This library is great! Its simplicity and its many presets save a lot of time and everything works great.
My question is simple:  Is there any way to easily reverse the order of the LEDs?

Thank you

**Comment by moose4lord** [comment]
You can add the REVERSE option at the end of the segSegment() statement.
```c++
ws2812fx.setSegment(0, 0, 9, FX_MODE_FADE, colors, 2000, REVERSE);
```
This option, and others, is covered in the User Guide.

**Comment by biccius** [comment]
Thanks, with some adaptations in my code it worked.
I thought there was a method at init that would do that but setSegment worked fine.

This issue can be closed.
