### ISSUE TITLE
Plain C implementation for general MCUs

### ISSUE THREAD

**Issue by j3qq4hch** [kitesurfer1404/WS2812FX#33]
Do you have a plain C implementation of all these effects not only for arduino-compatible hardware but for general use? I mean,  something, you can use with stm32 or msp430 with just C compiller and without neopixel or fastled libraries, as they seem to be useless outside arduino environment. 
If no - would you like me to make such an implementation?

**Comment by kitesurfer1404** [comment]
Hi. Sorry, that's not the purpose of this library. I guess it might be quite easy to port the effects themselves to plain C when you have the background-code of storing the data and pushing them to the pixels. But that will end in something similar to the Adafruit lib, I guess.

I'll close this one. But if you provide some links to plain C WS2812 stuff, I'll link to it in the README so other interested people find their way to that.
