### ISSUE TITLE
serial_conrol crashes at <255 LEDs

### ISSUE THREAD

**Issue by QubeCode** [kitesurfer1404/WS2812FX#330]
I have an LED strip with 300 LEDs. I wat to control it through the serial monitor. Everything works just fine when I use only 255 LEDs or less, but as soon as I use more, everything is black.
P. S.: auto_mode_cycle.ino works with 300 LEDs.

**Comment by moose4lord** [comment]
You've run out of memory. An Arduino only has 2048 bytes of dynamic memory, and with the serial_control sketch there just isn't enough memory to accommodate 300 LEDs.

You can reduce the number of segments available by changing your WS2812FX instantiation to this:
```c++
WS2812FX ws2812fx = WS2812FX(LED_COUNT, LED_PIN, NEO_GRB + NEO_KHZ800, 1, 1);
```
which will free up some memory and allow you to drive 300 LEDs.
