### ISSUE TITLE
Random blinking on ESP-01

### ISSUE THREAD

**Issue by GH0st3rs** [kitesurfer1404/WS2812FX#332]
Hi. I uploaded it to ESP-01 and noticed a blinking while it should be static. A had attached DSO-TC2 то GPIO2 directly and as you can see the logic level is unstable.

![photo_2023-03-27_23-48-00](https://user-images.githubusercontent.com/20622766/228074587-73e9be59-abba-40fb-8f5e-d70a6ea5f87a.jpg)

The frequency of brightness blinks coincides with the appearance of such high-level flashes. Is it possible that this is a software bug inside the library or components?

**Comment by moose4lord** [comment]
Are you referring to the LED on the ESP-01? That LED is wired to GPIO2, so it will blink whenever GPIO2 is toggled. GPIO2 is toggled when programming the ESP-01 with your UART interface, and is also briefly pulled high when the ESP-01 is booted, so that may be what you're seeing. What sketch are you running?

**Comment by GH0st3rs** [comment]
I'm using default sketch example "webserver" . And this effect when esp disconnected from uart

**Comment by moose4lord** [comment]
Do you mean the esp8266_webinterface example sketch?

**Comment by GH0st3rs** [comment]
Exactly

**Comment by moose4lord** [comment]
On an ESP-01 the onboard LED wired to GPIO2 will flash at regular intervals depending on the ```ws2812fx.setSpeed(1000);``` setting. This is normal. Even when the mode is set to FX_MODE_STATIC, the library continues to refresh the WS2812 LEDs periodically. If you use the web interface to change the "speed" parameter, you'll see the the onboard LED flash rate change as well.

**Comment by GH0st3rs** [comment]
But how It will affect to the signal level? As you can see the screenshot there is 3 high level signal package and 1 with medium level. All of those 4 packages contain the same code: 
Constant color for all LEDs. The difference only that we have a random signal level here

**Comment by GH0st3rs** [comment]
> I should mention that the ESP-01 comes in two varieties. The ESP-01 and the ESP-01S. The ESP-01S has the onboard blue LED wired to GPIO2, but the older ESP-01 does not. So it looks like you have an ESP-01S.

This is correct. But what the reason as different signal level for random packages?

**Comment by moose4lord** [comment]
I think you're undersampling the waveform on your oscilloscope. 500ms/div is way too slow to capture the true waveform. It takes 30us to update one WS2812 led, so if you have 30 LEDs, the entire waveform is only 900us long, so you'll need to crank the sample rate to at least 1ms/div to see that.

**Comment by moose4lord** [comment]
Hmmmm...I'm not sure what you're trying to show me. Driving 600 LEDs takes about 18ms (600 x 30us), which is what seems to be shown in your first photo, so that makes sense. But that represents 14400 individual pulses (600 x 3 colors x 8 bits per color), which is impossible for your oscilloscope to display at the time scales you've shown. You'll need to crank up the oscilloscope's time scale if you want to capture the waveform with good fidelity. I think your DSO-TC2 can do 10us/div, which should give you a good picture of the waveform.

As an aside, do you have a resistor between the ESP-01 GPIO2 and the first WS2812 Din pin? It can really help dampen under/over shoot noise and make the waveform look much better. I use a 100 ohm resistor.

**Comment by mindforger** [comment]
from the datasheet of the scope 

Analog Bandwidth: 0-200 kHz 

way too low for the actual data to be measureable
you need at least 800khz

**Comment by moose4lord** [comment]
Yikes! You're right @mindforger. I missed that in the datasheet.

**Comment by mindforger** [comment]
i know this runs well off topic but if you know a good and cheap 1Mhz (or bettter) Osc, i am searchign for years now XD nothin below 250 €/$ that is somewhat usefull

**Comment by GH0st3rs** [comment]
Yes I'm pretty sure about led count. But maybe there is any thing else that I can to check this days?

**Comment by mindforger** [comment]
you can adda significant delay between updates and see if that fixes the issue ... there was an issue in the past where the espressif chip would cause interruptions during an update if you do not yield enough between updates

**Comment by moose4lord** [comment]
Sorry, I misunderstood the problem. I thought it was the ESP-01's onboard LED that was "blinking" strangely, not the actual WS2812 LEDs. I do not notice any WS2812 blinking in any of my ESP installations. Although my largest installation has only 300 LEDs, so I have no experience with 600 LEDs.

The only thing I can think of is it's some kind of power distribution problem. A strip of 600 LEDs would have a considerable voltage drop from one end to the other, unless you're injecting power at intermediate locations along the length of the strip. Although I would expect FastLED to show the same blinking issue if that were the case. Still it may be wise to check the 5V voltage on the far end of the LED strip.

Are you using a 3.3V-to-5V level shifter between the ESP-01 and the WS2812s?

**Comment by GH0st3rs** [comment]
Yes I have a level shifter, but it doesn't mater, because the same effect with or without it. I recorded a video how it look.

In the example I used "Twinkle" pattern, and it turned on a random colors for random leds while in update process. 
https://user-images.githubusercontent.com/20622766/229296469-9114499c-dfa7-4e7f-9f12-56a646d87c95.MOV

**Comment by moose4lord** [comment]
Wow, that's so odd. Thanks for the video, that shows the issue pretty clearly. I'm still not sure what the problem could be. I have my ESP-01S connected to 64 WS2812Bs and I don't see any strange blinking. If I set the led count to 600 with ```#define LED_COUNT 600``` to trick it into thinking it's driving 600 LEDs, I still don't see a problem. You've tried setting LED_COUNT to something small, like 30, and you still see the issue, right?

I can only guess that there's some noise being injected into your system somehow. Double check that your ESP-01, level shifter and WS2812s are sharing a common ground. And have a pretty beefy decoupling capacitor (a few hundred micro farads) across the +5V and GND connections of the LED strip. What kind of power supply and level shifter are you using?

**Comment by GH0st3rs** [comment]
@moose4lord Can you share your сonnection scheme? I just want to double check that's everything is ok.
> I have my ESP-01S connected to 64 WS2812Bs

**Comment by moose4lord** [comment]
This is what my circuit looks like:
![Screen shot](https://user-images.githubusercontent.com/15672113/229313637-fc13ddcc-08c3-44b7-93ac-9639742b1737.png)

**Comment by GH0st3rs** [comment]
Ok, I think it's not a codding problem. I was trying to use different circuits with IRFZ44N as level shifter and without it, and I noticed that time to time it has some interference's. Also I met the problem that time-to-time the ESP may reboot or crashed while it connected to wifi, as I understand it something wrong with arduino wifi core for ESP because it based on an oldest ESP API.

I'm Attaching the my circuit that works not bad with minimal random blinking. I know that it looks strange and it looks like P-chanel mosfet. But In my point of view the 74hct125N level-shifter DIP-14 too large for this project. I also tried to implement i2c-version of level shifter like bs138.
![Screenshot from 2023-04-19 14-08-48](https://user-images.githubusercontent.com/20622766/233070423-baf1ef79-7f87-4f7e-becb-7e81b1b6bbf7.png)

I also found this project will try to implement it 
https://www.instructables.com/How-to-Controls-WS2812B-Using-ESP-01-Arduino-ESP82/

**Comment by moose4lord** [comment]
Your MOSFET circuit looks a little unconventional to me. Shouldn't there by a pull down resistor on the source?

I never had good luck creating a level shifter with discrete components. I tried using a BJT once and it was a nightmare to get the bias and drive currents right. I think it's definitely worth a few cents to buy a non-inverting buffer to drive the WS2812s. If you're concerned about size, try a dual gate driver like a 74HCT2G34. It will save you a lot of headache.
