### ISSUE TITLE
PSRAM useful for WS2812FX?

### ISSUE THREAD

**Issue by EherXtrem** [kitesurfer1404/WS2812FX#339]
I have an ESP32-S3-DevKitC-1-N8R8 with 8MB Octal PSRAM. Is it possible to use the pseudo SRAM to add more LEDs?

**Comment by moose4lord** [comment]
At the moment, I don't think so. After just a cursory scan of the ESP32 RMT driver included with the NeoPixel library (which WS2812FX extends), it  doesn't look like there's any support for using PSRAM to store LED data.

Depending on what else is gobbling up memory in your sketch, you may be able to use PSRAM for other features of your sketch (frame buffers, large dataset storage and such), and so free up some regular SRAM to use for LEDs.

**Comment by EherXtrem** [comment]
THX for your support :)
