### ISSUE TITLE
Changing position of the diode 0

### ISSUE THREAD

**Issue by chakjer** [kitesurfer1404/WS2812FX#343]
Hi,
I have 200 diodes in square room but 0 position is not in the corner.
Is there a chance to shift the start diode left/right?
I have tried to configure in 2 segments, but speed is different and effect is not continuously. 
I'm using WS2812FXT.

**Comment by moose4lord** [comment]
Issue #284 addresses a similar situation. You may be able to adapt the solution proposed there for use with WS2812FXT.

**Comment by chakjer** [comment]
Hi,
Thx for hint.
I tried to customShow for ws2812fxt.v1 and ws2812fxt.v2 but no transition effects but it is obvious.
Next disabled in WS2812FXT in _show `dest->Adafruit_NeoPixel::show();` and create function 
```
void shiftLED(void)
{
  for (int i = 0; i < ws2812fx_p.getNumBytes(); i++)
  {
    ws2812fx_p.setPixelColor(i, ws2812fxt.dest->getPixelColor(ledMap[i]));
  }
  ws2812fx_p.Adafruit_NeoPixel::show();
}
```
and running after `ws2812fxt.service();` but  it doesn't work well. 
There is less brightness and effects are displayed twice, normal and shifted.

**Comment by chakjer** [comment]
Hi,
It works, but there is some problem with effects. In my case leds are white.
1)FX_MODE_RAINBOW_CYCLE  in both directions
2)FX_MODE_RUNNING_RANDOM, FX_MODE_MERRY_CHRISTMAS, FX_MODE_HALLOWEEN, FX_MODE_RUNNING_RANDOM2  in revers direction

It is not a problem for me i just disabled effect or direction but i want you let you know.
Thx anyway for resolving problem.

**Comment by moose4lord** [comment]
That's odd. I tried the effects that were giving you a problem and they seem to work ok for me. If you paste a copy of the sketch that isn't working correctly for you, I can look into it further.

**Comment by chakjer** [comment]
Hi, 
My sketch [esp32.zip](https://github.com/kitesurfer1404/WS2812FX/files/13711984/esp32.zip)

**Comment by moose4lord** [comment]
Yikes, there's a lot there. I don't use PlatformIO or PubSub, and don't have a development board with an  SD card, so couldn't compile and run your sketch. If you can reproduce the issue you're seeing with my simpler example sketch, I'd be happy to look at it.

**Comment by moose4lord** [comment]
This issue seems stale, so I'm closing. Feel free to reopen if you think it needs more attention.
