### ISSUE TITLE
is it possible to create an initial instance without parameters

### ISSUE THREAD

**Issue by AutoPlantBali** [kitesurfer1404/WS2812FX#347]
WS2812FX ws2812fx = WS2812FX(config.ledCount, WS2812FX_PIN, NEO_GRB + NEO_KHZ800);

to

WS2812FX ws2812fx;

I want to set the number of LEDs in the setup function because the number of dynamic LEDs is according to the configuration file or is there a function to scan the number of installed LEDs?

**Comment by AutoPlantBali** [comment]
finally I have found the solution, with the setLength function.

thanks you..

**Comment by moose4lord** [comment]
Great! 
There are also setPin() and updateType() functions to dynamically change the GPIO pin and neoPixelType at runtime.
Just FYI.
