### ISSUE TITLE
playing a bit

### ISSUE THREAD

**Issue by ldijkman** [kitesurfer1404/WS2812FX#350]
playing a bit with auto mdns list

do not understand yet why there is no on off
and why select color background of input is not colored to selected

https://ldijkman.github.io/async-esp-fs-webserver/

![Screenshot from 2024-03-22 05-21-58](https://github.com/kitesurfer1404/WS2812FX/assets/45427770/c1dcdb0b-60dd-41af-903b-24c00e91bfd8)

**Comment by moose4lord** [comment]
Are you trying to use the esp8266_interface example sketch with webSockets? If so, that won't work. The example sketch is expecting ws2812 data to come across the network as simple HTTP query parameters. Like this:
```c++
http://ws2812.local/set?c=1946112
```
A webSocket data frame is incompatible. You'd need to write some custom code to translate the webSocket data into parameters that the esp8266_interface code can understand.

**Comment by ldijkman** [comment]
It is working
Ok if you click on rgb 000 it is off
Maybe a button for off
I was expecting color in rgb button



![Screenshot_20240322-184357_Chrome](https://github.com/kitesurfer1404/WS2812FX/assets/45427770/e74a9005-6b7d-42be-ac7f-0d599a55ca2b)

**Comment by moose4lord** [comment]
Closing this issue as part of periodic cleanup.
