### ISSUE TITLE
flash install from bowser on 4mb ESP8266 12E/12F gpio2=D4 20leds

### ISSUE THREAD

**Issue by ldijkman** [kitesurfer1404/WS2812FX#351]
a test maybe ...

on
- https://ldijkman.github.io/async-esp-fs-webserver/
is a button
- Connect & Install on 4mb ESP2866 12E / 12F ws2812 led strip on gpio2 = D4 20 leds

test to Easy flash ESP from in browser

server contains /2812.html  or http://ws2812.local/2812.html
wich can set led color for now

20 leds gpio2 = D4

anyone willing to try / test it?

![Screenshot from 2024-03-23 10-38-33](https://github.com/kitesurfer1404/WS2812FX/assets/45427770/ce6a0437-5eef-4426-ae3d-86c987ea20f2)

edit the webserver file on the server ace editor

![Screenshot from 2024-03-23 10-48-05](https://github.com/kitesurfer1404/WS2812FX/assets/45427770/34064375-d687-4917-b390-6965d3b5efda)

**Comment by ldijkman** [comment]
video with a bit more chaotic info

https://youtu.be/YS3hWK9fHIE

**Comment by ldijkman** [comment]
bit better video
- flash from browser
- https://youtu.be/5SzWE3oxlLI

**Comment by ldijkman** [comment]
bit further 
got some buttons now

new video https://youtu.be/xio0c5hPp5I?si=v2go6OXg9qnJbuRZ

https://ldijkman.github.io/async-esp-fs-webserver/

![Screenshot from 2024-03-25 05-49-57](https://github.com/kitesurfer1404/WS2812FX/assets/45427770/48373492-dd53-4143-8413-f2b442aaa631)

**Comment by ldijkman** [comment]
![Screenshot from 2024-03-26 06-12-41](https://github.com/kitesurfer1404/WS2812FX/assets/45427770/991bf37b-d523-4f8a-be60-cf5482050e08)

**Comment by ldijkman** [comment]
added settings feedback
speed brightness mode

https://ldijkman.github.io/async-esp-fs-webserver/

![Screenshot from 2024-03-27 04-10-26](https://github.com/kitesurfer1404/WS2812FX/assets/45427770/92b1a2b4-eb0d-4960-a77c-5bcdd74304f2)

**Comment by ldijkman** [comment]
added a speed slider

https://ldijkman.github.io/async-esp-fs-webserver/

![Screenshot from 2024-03-27 17-44-07](https://github.com/kitesurfer1404/WS2812FX/assets/45427770/e3e71442-1f92-4dd6-a498-f8a8b67a60e5)

**Comment by ldijkman** [comment]
some changes 
higlight button on auto play cycle

https://ldijkman.github.io/async-esp-fs-webserver/

![Screenshot from 2024-03-30 07-52-44](https://github.com/kitesurfer1404/WS2812FX/assets/45427770/b31fa864-80bb-444d-9eb5-f1c6d09dc927)

**Comment by moose4lord** [comment]
Closing this issue as part of periodic cleanup.
