### ISSUE TITLE
Big thanks!

### ISSUE THREAD

**Issue by renat2985** [kitesurfer1404/WS2812FX#4]
Thank you very much for your project!
I use it in my project. If you're interested you can see here:

- https://www.youtube.com/watch?v=71gqJfknq84&index=9&list=PL6NJTNxbvy-IPTDQk8XjTV41oRrFafrRi
- https://github.com/renat2985/rgb

**Comment by kitesurfer1404** [comment]
Thank you. 
I'll add a list of projects using WS2812FX and add your project.
