### ISSUE TITLE
Add support for animation direction, and virtual strips

### ISSUE THREAD

**Issue by fonix232** [kitesurfer1404/WS2812FX#42]
Okay, since the title is limited, let me explain the virtual strips part.

Say you have a few various shaped "strips", "bits", "rings", etc. made of one or more WS2812 LEDs. Say you want to control them all, but from a single pin (because your project includes more and more devices that an ESP8266 or an Arduino can support).

So it would be nice to be able to define a single strip (say, 3x 24-LED rings in series, first one connected to a pin, second one connected to first one's output, et cetera), and be able to make segments out of it, animated separately. I'm thinking something similar to this:

```cpp
#include <WS2812FX.h>

#define LED_COUNT 72
#define LED_PIN 15

WS2812FX strip= WS2812FX(LED_COUNT, LED_PIN, NEO_GRB + NEO_KHZ800);
WS2812FXSegment segment1 = strip.segment(0 ,23);
WS2812FXSegment segment2 = strip.segment(24, 47);
WS2812FXSegment segment3 = strip.segment(48, 71)

void setup() {
  strip.init();
  strip.setBrightness(255);  // Modifying the strip object will modify all segments too
  strip.setSpeed(100);
  strip.setMode(FX_MODE_FLASH_SPARKLE);

  segment2.setMode(FX_MODE_RAINBOW_CYCLE); // setting the segment options after the strip will override those settings for said segment
  segment2.setSpeed(150);

  strip.start(); // starting the strip should go over all defined segments and start them separately
}

void loop() {
  strip.service(); // servicing the strip should go over all defined segments and service them too
}
```

And about the direction of animations. Especially on rings, alignment is a bitch. Say you want two 24-LED rings do the same animation, and attach them back to back. Well you can't, since the directions won't match. So it would be nice if separate WS2812FX objects (and, if implemented, segments too) could have a direction set (either NORMAL, which means the current direction and addressing `0..n`, and REVERSE, which means reversed direction addressing `n..0`).

**Comment by kitesurfer1404** [comment]
I fully understand and I need a this in the near future for my Christmas decoration. I have three idetical windows that will get strips oround them. Running in circles etc. is a well needed improvement.
I can not promise to implement this immediately. But it's on the list.

**Comment by fonix232** [comment]
Technically speaking, segmenting (at least in a properly OO language, say, C# or Java) is easy to solve - each segment is practically a WS2812FX object, but it maps only parts of the parent object's LEDs (such as, it translates e.g. 48 to 0, 49 to 1, 71 to 23, to extend my example).

Animation direction is again relatively simple, and I might give it a go in the near future.

**Comment by jaekar99** [comment]
I would totally dig this.. I build ws2812 clocks..   I could break out the different segments for each of the hands and other animation..

I absolutely love this library.. It has been useful in many projects..  Your work makes mine a pleasure.


![img_20170904_071028419](https://user-images.githubusercontent.com/29959139/30351224-8e3e260a-97d7-11e7-8072-a28b5a6a51fd.jpg)
![img_20170826_144611188](https://user-images.githubusercontent.com/29959139/30351225-8e424e7e-97d7-11e7-9c72-0a8e7812391b.jpg)
![img_20170727_152327848](https://user-images.githubusercontent.com/29959139/30351226-8e463d04-97d7-11e7-9330-d0a82e393efc.jpg)
