### ISSUE TITLE
speed calculation

### ISSUE THREAD

**Issue by 10der** [kitesurfer1404/WS2812FX#52]
Hi!

look like speed calculation wrong (IMHO)
can you change speed calculation like this:

//SEGMENT_RUNTIME.next_time = now + max(delay, 20);
SEGMENT_RUNTIME.next_time = now + map(delay, 0, 255, 20, 1000);

Thank you!

**Comment by moose4lord** [comment]
The "delay" parameter returned from the mode functions is a bit chaotic. I think Harm calculated them empirically after doing some experimentation. I have changed the delay calculation in my fork of WS2812FX to be, I think, more straightforward. The delay is calculated to be the delay between 'ticks' of the animation (most of the time it is SPEED/LED_COUNT). So if your LED_COUNT=100 and you set SPEED=2000, then delay=20ms. The SPEED parameter ends up being the duration of one cycle of animation (in milliseconds). This is the only way I could get animations in separate segments to synchronize.

Unfortunately, it kind of breaks the SPEED parameter. With Harm's method, SPEED's range is 0-255, and animations get faster when you increase the SPEED parameter. With my method, SPEED's range is 0-65535, and animations get SLOWER when you increase the SPEED parameter.

Anyway, I'll send Harm a pull request and he can incorporate my changes into the code if he thinks they won't be too disruptive.
