### ISSUE TITLE
esp8266 hang and reset after running effect

### ISSUE THREAD

**Issue by phutruong1801** [kitesurfer1404/WS2812FX#66]
Hi everyone. 
I need a little help about my project 
i'm using esp 8266 node mcu  to control 2 button, DHT22 and ws2812 via node-red MQTT pubsubclient
the problem is my esp being hang and sometime it will reset the esp. sometime not. 
i believe that the WS2112FX cause the hang. 
here is my code. please help me fix it. i waste 2 days to find the problem but i fall in love with the effect of WS2812FX

#include <PubSubClient.h>
#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <WiFiUdp.h>
#include <ArduinoOTA.h>
#include <SoftwareSerial.h>
#include "DHT.h"
#include <Wire.h>
#include <WS2812FX.h>
#define LED_COUNT 216
#define LEDPIN D7
const int SPEED = 1000;

const char* ssid = "WifiChua";
const char* password = "xvideos.com";
const char* mqtt_server = "xxx.xxx.xx.xx";
int r;
int g;
int b;
const int Den_Pin1 = D1;
const int Den_Pin2 = D2;
const int Button1 = D5;
const int Button2 = D6;
int  den1status = HIGH;
int  den2status = HIGH;
int  State1 = LOW;
int  State2 = LOW;
//----------
#define DHTPIN D8
#define DHTTYPE DHT22
//boolean debug = false;
boolean debug = true;
WiFiClient espClientroom;
DHT dht(DHTPIN, DHTTYPE);
unsigned long lastMeasure = 0;
unsigned long lastMillis = 0;
WS2812FX ws2812fx = WS2812FX(LED_COUNT, LEDPIN, NEO_GRB + NEO_KHZ800);
//long lastMsg = 0;
//char msg[50];
//int value = 0;
PubSubClient client(espClientroom);
void nhand1(char* tp, byte* nd, unsigned int length) {
  String topic(tp);
  String noidung = String((char*)nd);
  noidung.remove(length);

  if (topic == "LED/dk")
  {
    const int EF = noidung.toInt();
    switch (EF) {
      case 1:
        ws2812fx.setMode(FX_MODE_RAINBOW);
        break;
      case 2:
        ws2812fx.setMode(FX_MODE_HALLOWEEN);
        break;
      case 3:
        ws2812fx.setMode(FX_MODE_RANDOM_COLOR);
        break;
      case 4:
        ws2812fx.setMode(FX_MODE_STATIC);
        break;
      case 5:
        ws2812fx.setMode(FX_MODE_STATIC);
        break;
      case 6:
        ws2812fx.setMode(FX_MODE_RAINBOW_CYCLE);
        break;
      case 7:
        ws2812fx.setMode(FX_MODE_DUAL_SCAN);
        break;
      case 8:
        ws2812fx.setMode(FX_MODE_CHASE_RAINBOW);
        break;
      case 9:
        ws2812fx.setMode(FX_MODE_RUNNING_RANDOM);
        break;
      case 10:
        ws2812fx.setMode(FX_MODE_CHASE_BLACKOUT_RAINBOW);
        break;
      case 11:
        ws2812fx.setMode(FX_MODE_COLOR_SWEEP_RANDOM);
        break;
      case 12:
        ws2812fx.setMode(FX_MODE_BLINK);
        break;
      case 13:
        ws2812fx.setMode(FX_MODE_BREATH);
        break;
      case 14:
        ws2812fx.setMode(FX_MODE_COLOR_WIPE);
        break;
      case 15:
        ws2812fx.setMode(FX_MODE_COLOR_WIPE_INV);
        break;
      case 16:
        ws2812fx.setMode(FX_MODE_COLOR_WIPE_REV);
        break;
      case 17:
        ws2812fx.setMode(FX_MODE_COLOR_WIPE_REV_INV);
        break;
      case 18:
        ws2812fx.setMode(FX_MODE_SINGLE_DYNAMIC);
        break;
      case 19:
        ws2812fx.setMode(FX_MODE_MULTI_DYNAMIC);
        break;
      case 20:
        ws2812fx.setMode(FX_MODE_SCAN);
        break;
      case 21:
        ws2812fx.setMode(FX_MODE_FADE);
        break;
      case 22:
        ws2812fx.setMode(FX_MODE_THEATER_CHASE);
        break;
      case 23:
        ws2812fx.setMode(FX_MODE_THEATER_CHASE_RAINBOW);
        break;
      case 24:
        ws2812fx.setMode(FX_MODE_RUNNING_LIGHTS);
        break;
      case 25:
        ws2812fx.setMode(FX_MODE_TWINKLE);
        break;
      case 26:
        ws2812fx.setMode(FX_MODE_TWINKLE_RANDOM);
        break;
      case 27:
        ws2812fx.setMode(FX_MODE_TWINKLE_FADE);
        break;
      case 28:
        ws2812fx.setMode(FX_MODE_TWINKLE_FADE_RANDOM);
        break;
      case 29:
        ws2812fx.setMode(FX_MODE_SPARKLE);
        break;
      case 30:
        ws2812fx.setMode(FX_MODE_FLASH_SPARKLE);
        break;
      case 31:
        ws2812fx.setMode(FX_MODE_HYPER_SPARKLE);
        break;
      case 32:
        ws2812fx.setMode(FX_MODE_STROBE);
        break;
      case 33:
        ws2812fx.setMode(FX_MODE_STROBE_RAINBOW);
        break;
      case 34:
        ws2812fx.setMode(FX_MODE_MULTI_STROBE);
        break;
      case 35:
        ws2812fx.setMode(FX_MODE_BLINK_RAINBOW);
        break;
      case 36:
        ws2812fx.setMode(FX_MODE_CHASE_WHITE);
        break;
      case 37:
        ws2812fx.setMode(FX_MODE_CHASE_COLOR);
        break;
      case 38:
        ws2812fx.setMode(FX_MODE_CHASE_RANDOM);
        break;
      case 39:
        ws2812fx.setMode(FX_MODE_CHASE_FLASH);
        break;
      case 40:
        ws2812fx.setMode(FX_MODE_CHASE_FLASH_RANDOM);
        break;
      case 41:
        ws2812fx.setMode(FX_MODE_CHASE_RAINBOW_WHITE);
        break;
      case 42:
        ws2812fx.setMode(FX_MODE_CHASE_BLACKOUT);
        break;
      case 43:
        ws2812fx.setMode(FX_MODE_COLOR_SWEEP_RANDOM);
        break;
      case 44:
        ws2812fx.setMode(FX_MODE_RUNNING_COLOR);
        break;
      case 45:
        ws2812fx.setMode(FX_MODE_RUNNING_RED_BLUE);
        break;
      case 46:
        ws2812fx.setMode(FX_MODE_LARSON_SCANNER);
        break;
      case 47:
        ws2812fx.setMode(FX_MODE_COMET);
        break;
      case 48:
        ws2812fx.setMode(FX_MODE_FIREWORKS);
        break;
      case 49:
        ws2812fx.setMode(FX_MODE_FIREWORKS_RANDOM);
        break;
      case 50:
        ws2812fx.setMode(FX_MODE_FIRE_FLICKER);
        break;
      case 51:
        ws2812fx.setMode(FX_MODE_FIRE_FLICKER_SOFT);
        break;
      case 52:
        ws2812fx.setMode(FX_MODE_FIRE_FLICKER_INTENSE);
        break;
      case 53:
        ws2812fx.setMode(FX_MODE_CIRCUS_COMBUSTUS);
        break;
      case 54:
        ws2812fx.setMode(FX_MODE_BICOLOR_CHASE);
        break;
      case 55:
        ws2812fx.setMode(FX_MODE_TRICOLOR_CHASE);
        break;
      case 56:
        ws2812fx.setMode(FX_MODE_ICU);
        break;
      default:
        break;
    }
  }
  if (topic == "LED/green")
  {
    g = noidung.toInt();

    setcolor();
  }
  if (topic == "LED/red")
  {
    r = noidung.toInt();

    setcolor();
  }
  if (topic == "LED/blue")
  {
    b = noidung.toInt();

    setcolor();
  }
  if (topic == "DEN/room1")
  {
    if (noidung == "1") {
      Serial.println("ON");
      digitalWrite(Den_Pin1, LOW);   // LED có sẵn trên NodeMCU bật ở mức 0(LOW)
      State1 = HIGH;
    }
    // Tắt LED nếu nhận được lệnh là 0
    if (noidung == "0") {
      Serial.println("OFF");
      digitalWrite(Den_Pin1, HIGH);  // LED tắt ở mức 1(HIGH)
      State1 = LOW;
    }
  }
  if (topic == "DEN/room2")
  {
    if (noidung == "1") {
      digitalWrite(Den_Pin2, LOW);
      State2 = HIGH;
    }
    if (noidung == "0") {
      digitalWrite(Den_Pin2, HIGH);
      State2 = LOW;
    }
  }
}
void setcolor()
{
  ws2812fx.setColor(g, r, b);
}
void checkbutton(void)
{
  if (digitalRead(Button1) == HIGH && State1 == LOW)
  {
    den1status = LOW;
    digitalWrite(Den_Pin1, den1status);
    State1 = HIGH;
    client.publish("DEN/room1", String(!digitalRead(Den_Pin1)).c_str());
    while (digitalRead(Button1) == HIGH)
    {
      yield();
    }
  }
  if (digitalRead(Button2) == HIGH && State2 == LOW)
  {
    den2status = LOW;
    digitalWrite(Den_Pin2, den2status);
    State2 = HIGH;
    client.publish("DENn/room2", String(!digitalRead(Den_Pin2)).c_str());
    while (digitalRead(Button2) == HIGH)
    {
      yield();
    }
  }
  if (digitalRead(Button1) == HIGH && State1 == HIGH)
  {
    den1status = HIGH;
    digitalWrite(Den_Pin1, den1status);
    State1 = LOW;
    client.publish("DEN/room1", String(!digitalRead(Den_Pin1)).c_str());
    while (digitalRead(Button1) == HIGH)
    {
      yield();
    }
  }
  if (digitalRead(Button2) == HIGH && State2 == HIGH)
  {
    den2status = HIGH;
    digitalWrite(Den_Pin2, den2status);
    State2 = LOW;
    client.publish("DEN/room2", String(!digitalRead(Den_Pin2)).c_str());
    while (digitalRead(Button2) == HIGH)
    {
      yield();
    }
  }
}
void setup() {
  int timeoutcounter = 0;
  Serial.begin(115200);
  dht.begin();
  WiFi.begin(ssid, password);
  pinMode(LEDPIN, OUTPUT);
  ws2812fx.init();
  ws2812fx.setBrightness(255);
  ws2812fx.setSpeed(SPEED);
  ws2812fx.setColor(0xFF5900);
  ws2812fx.setMode(FX_MODE_STATIC);
  ws2812fx.start();
  pinMode(Den_Pin1, OUTPUT); pinMode(Den_Pin2, OUTPUT);
  pinMode(Button1, INPUT); pinMode(Button2, INPUT);
  digitalWrite(Den_Pin1, den1status); digitalWrite(Den_Pin2, den2status);

  while (WiFi.status() != WL_CONNECTED) {
    timeoutcounter++;
    delay(500);
    if (timeoutcounter >= 30) {
      if (debug) {
        Serial.println("Failed to connect to wireless - sleeping for 5 minutes");
        delay(5000);
      }
    }
  }
  client.setServer(mqtt_server, 1883);
  client.setCallback(nhand1);
  ArduinoOTA.setPassword((const char *)"123");
  ArduinoOTA.onStart([]() {
    Serial.println("Start");
  });
  ArduinoOTA.onEnd([]() {
    Serial.println("\nEnd");
  });
  ArduinoOTA.onProgress([](unsigned int progress, unsigned int total) {
    Serial.printf("Progress: %u%%\r", (progress / (total / 100)));
  });
  ArduinoOTA.onError([](ota_error_t error) {
    Serial.printf("Error[%u]: ", error);
    if (error == OTA_AUTH_ERROR) Serial.println("Auth Failed");
    else if (error == OTA_BEGIN_ERROR) Serial.println("Begin Failed");
    else if (error == OTA_CONNECT_ERROR) Serial.println("Connect Failed");
    else if (error == OTA_RECEIVE_ERROR) Serial.println("Receive Failed");
    else if (error == OTA_END_ERROR) Serial.println("End Failed");
  });
  ArduinoOTA.begin();
  Serial.println("Ready");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
}

void reconnect() {
  while (!client.connected()) {
    if (client.connect("ESP8266Clientroom")) {
      client.publish("arduino_2_data", "OnLine");
      client.subscribe("LED/dk");
      client.subscribe("LED/green");
      client.subscribe("LED/red");
      client.subscribe("LED/blue");
      client.subscribe("DEN/room1");
      client.subscribe("DEN/room2");

    } else {
      if (debug) {
        Serial.print("failed, rc=");
        Serial.print(client.state());
        Serial.println(" try again in 5 seconds");
      }
      delay(5000);
    }
  }
}
void loop()
{
  ws2812fx.service();
  client.loop();

  ArduinoOTA.handle();
  if (!client.connected()) {
    reconnect();
  }
  if (millis() - lastMillis > 100) {
    checkbutton();
    lastMillis = millis();
  }
  unsigned long now = millis();
  if (now - lastMeasure > 30000) {
    tempandhump();
    lastMeasure = now;
  }
}
void tempandhump(void)
{
  float h = dht.readHumidity();
  // Read temperature as Celsius (the default)
  float t = dht.readTemperature();
  float f = dht.readTemperature(true);
  // Check if any reads failed and exit early (to try again).
  if (isnan(h) || isnan(t) || isnan(f)) {
    Serial.println("Fall to read sensor");
    return;
  }
  float hic = dht.computeHeatIndex(t, h, false);
  static char temperatureTemp[7];
  dtostrf(hic, 6, 2, temperatureTemp);
  static char humidityTemp[7];
  dtostrf(h, 6, 2, humidityTemp);
  client.publish("Mainroom/Temp", temperatureTemp);
  client.publish("Mainroom/Hum", humidityTemp);
  Serial.print("Humidity: ");
  Serial.print(h);
  Serial.print(" %\t Temperature: ");
  Serial.print(t);
  Serial.print(" *C ");
  Serial.print(f);
  Serial.print(" *F\t Heat index: ");
  Serial.print(hic);
  Serial.println(" *C ");
  delay(50);
}

**Comment by moose4lord** [comment]
I feel your pain. I tried to get MQTT and WS2812FX to work together, but finally gave up. I could never get it to work reliable, my ESP8266 would reboot at random times. I poked through the crash dumps, but wasn't able to figure out what was causing the reboots. Sorry, I wish I could be more help.

I think if I were to pursue it again, I would separate the MQTT functions from the WS2812FX functions, having the ESP8266 handle the MQTT part and a separate Arduino take care of the LEDs. Just a thought.

**Comment by tobi01001** [comment]
Maybe this helps? 

https://github.com/euphi/ESP_Homie_WS2812FX

**Comment by synssins** [comment]
Have any of you looked into McLighting v2? It uses the ws2812fx library and adds REST, MQTT and WebSockets, as well as a nifty webUI for controlling it.

**Comment by moose4lord** [comment]
I started out using McLighting. It's quite nice. Easy to use and now it saves the last setup to eeprom, so it might be all you need. Doesn't support segments though :(

**Comment by superbool** [comment]
I also encountered the problem，actually not the mqtt or the ws2812fx problem  but the DHT.At least it is to me.  When I removed all code of  DHT, it worked fine. I found out the four lines have problems:
```
dtostrf(hic, 6, 2, temperatureTemp);
dtostrf(h, 6, 2, humidityTemp);
Serial.print(h);
Serial.print(t);
```
but I don't know why and which line make it crashed.

I only subscribe one topic ,but you subscribe several topics, I don't know it is affect.

here is my code, it works fine:
```
#include <ESP8266WiFi.h>
#include <PubSubClient.h>
#include <WS2812FX.h>

#define LED_COUNT 300
#define LED_PIN 2
#define TIMER_MS 5000

const char *ssid = "xxxx";
const char *password = "xxx";

const char *mqtt_server = "xxxx";
const unsigned int mqtt_port = xxxx;
const char *mqtt_username = "xxx";
const char *mqtt_password = "xxxx";
long lastMsg = 0;
char msg[50];
int value = 0;
unsigned long last_change = 0;
unsigned long now = 0;
const uint32_t colors[] = {RED, BLUE, WHITE};
const uint32_t heart_colors[] = {RED, WHITE, BLACK};
const uint32_t colors_black[] = {BLACK};

WiFiClient espClient;
PubSubClient client(espClient);
WS2812FX ws2812fx = WS2812FX(LED_COUNT, LED_PIN, NEO_GRB + NEO_KHZ800);

void setup_ws2812()
{
    ws2812fx.init();
    ws2812fx.setBrightness(255);
    ws2812fx.setSpeed(200);
    ws2812fx.setColor(0x000000);
    ws2812fx.setMode(FX_MODE_STATIC);
    ws2812fx.setSegment(0, 0, 53, 0, colors_black, 1000, false);
    ws2812fx.start();
}

void setup_wifi()
{
    delay(10);
    // We start by connecting to a WiFi network
    Serial.println();
    Serial.print("Connecting to ");
    Serial.println(ssid);

    WiFi.begin(ssid, password);

    while (WiFi.status() != WL_CONNECTED)
    {
        delay(500);
        Serial.print(".");
    }

    Serial.println("");
    Serial.println("WiFi connected");
    Serial.println("IP address: ");
    Serial.println(WiFi.localIP());
}

uint *parseData(String str)
{
    static uint data[5];
    uint r = 0, t = 0;
    for (uint i = 0; i < str.length(); i++)
    {
        if (str.charAt(i) == ';')
        {
            data[t] = str.substring(r, i).toInt();
            r = (i + 1);
            t++;
        }
    }
    return data;
}

void callback(char *topic, byte *payload, uint length)
{
    Serial.print("Message arrived [");
    Serial.print(topic);
    Serial.print("] ");
    String str = "";
    for (uint i = 0; i < length; i++)
    {
        str += (char)payload[i];
    }
    Serial.print(str);
    Serial.println();

    uint *data = parseData(str);
    if (data[0] == 1)
    { 
        ws2812fx.setPixelColor(data[1], data[2], data[3], data[4]);
        ws2812fx.show();
    }
    else if (data[0] == 2)
    { 
        uint segment = data[1];
        if (segment == 0)
        { 
            ws2812fx.setSegment(0, 0, 53, data[2], data[4] == 1 ? colors : colors_black, data[3], false);
        }
        else if (segment == 1)
        { 
            ws2812fx.setSegment(1, 54, 118, data[2], data[4] == 1 ? heart_colors : colors_black, data[3], false);
        }
        else if (segment == 2)
        { 
            ws2812fx.setSegment(2, 119, 159, data[2], data[4] == 1 ? colors : colors_black, data[3], false);
        }else if (segment == 3)
        { 
            ws2812fx.setSegment(3, 173, 248, data[2], data[4] == 1 ? colors : colors_black, data[3], false);
        }else {
            ws2812fx.resetSegments();
        }
    }
}

void reconnect()
{
    // Loop until we're reconnected
    while (!client.connected())
    {
        Serial.print("Attempting MQTT connection...");
        // Attempt to connect
        if (client.connect("ESP8266Client", mqtt_username, mqtt_password))
        {
            Serial.println("connected");
            client.subscribe("light_up_led");
            // Once connected, publish an announcement...
            client.publish("esp_msg", "starting", true);
            // ... and resubscribe
        }
        else
        {
            Serial.print("failed, rc=");
            Serial.print(client.state());
            Serial.println(" try again in 5 seconds");
            // Wait 5 seconds before retrying
            delay(5000);
        }
    }
}

void setup()
{
    pinMode(LED_BUILTIN, OUTPUT); // Initialize the BUILTIN_LED pin as an output
    Serial.begin(9600);
    setup_wifi();
    client.setServer(mqtt_server, mqtt_port);
    client.setCallback(callback);
    setup_ws2812();
}

void loop()
{
    //mqtt
    if (!client.connected())
    {
        reconnect();
    }
    client.loop();

    ws2812fx.service();

}
```

**Comment by moose4lord** [comment]
I think this conversation has run its course. Closing.
