### ISSUE TITLE
Individual Pixel control

### ISSUE THREAD

**Issue by danbicks** [kitesurfer1404/WS2812FX#69]
Would be nice to include standard method of writing to individual neo pixels in non effect mode.

Maybe there already could not see a specific function.

Dans

**Comment by tobi01001** [comment]
The class is based on the Adafruit neopixel class. You just need to call `WS2812FX::setPixelColor(pixel, ....)` - of course without calling service and/or trigger which may override immediatly with the current effect.

**Comment by danbicks** [comment]
Awesome,

Big thanks

Dans
