### ISSUE TITLE
Update PlatformIO library

### ISSUE THREAD

**Issue by Munken** [kitesurfer1404/WS2812FX#84]
The WS2812FX on PlatformIO is from the 7/11-2017 and suffers from the issue described here:
https://github.com/kitesurfer1404/WS2812FX/issues/58

This was fixed with pull request 65 in January.
https://github.com/kitesurfer1404/WS2812FX/pull/65

Would it be possible to upload a new version to PlatformIO?

**Comment by moose4lord** [comment]
I don't anything about PlatformIO, but it seems like changing the version in library.json would trigger a refresh of the PlatformIO library repository. I have done this. Let me know if it works.
