### ISSUE TITLE
FreeRTOS Port

### ISSUE THREAD

**Issue by pcsaito** [kitesurfer1404/WS2812FX#88]
I'm working on a FreeRTOS port. 
https://github.com/pcsaito/WS2812FX-rtos

There are interest in trying to unify? or at least make a common part with the animations code?

Thanks!

**Comment by kitesurfer1404** [comment]
There is. Feel free to suggest any ideas on that. But be aware of sudden changes in WS2812FX, because it's under heavy construction by @moose4lord and I have some ideas to implement, too.
